const toggle=document.querySelector('.nav-toggle');
const navigation=document.querySelector('.nav-links');
function closeMenu(){navigation?.classList.remove('open');toggle?.setAttribute('aria-expanded','false');}
if(toggle&&navigation){toggle.addEventListener('click',()=>{const open=navigation.classList.toggle('open');toggle.setAttribute('aria-expanded',String(open));});navigation.querySelectorAll('a').forEach(link=>link.addEventListener('click',closeMenu));document.addEventListener('keydown',event=>{if(event.key==='Escape'&&navigation.classList.contains('open')){closeMenu();toggle.focus();}});window.addEventListener('resize',()=>{if(window.innerWidth>700)closeMenu();});}
const practice={design:{word:'Make it clear.',note:'Ideas → experiences',description:'UX, interaction, and visual systems that make complex ideas easier to use.',index:'01 / 03'},prototype:{word:'Make it tangible.',note:'Explore → iterate',description:'From Figma to Figma Make: testing interactions and refining ideas through prototypes.',index:'02 / 03'},build:{word:'Make it work.',note:'Design → development',description:'HTML, CSS, JavaScript, and AI-assisted development to bring designs into the browser.',index:'03 / 03'}};
const tabs=[...document.querySelectorAll('.approach-tabs [role=tab]')];
function selectPractice(tab){const mode=tab.dataset.mode;const content=practice[mode];tabs.forEach(item=>{const active=item===tab;item.setAttribute('aria-selected',String(active));item.tabIndex=active?0:-1;});const art=document.querySelector('.approach-art');art.dataset.mode=mode;art.querySelector('.art-word').textContent=content.word;art.querySelector('.art-note').textContent=content.note;document.querySelector('.approach-index').textContent=content.index;const panel=document.querySelector('.approach-description');panel.textContent=content.description;panel.setAttribute('aria-labelledby',tab.id);}
tabs.forEach((tab,index)=>{tab.addEventListener('click',()=>selectPractice(tab));tab.addEventListener('keydown',event=>{let next;if(event.key==='ArrowRight')next=(index+1)%tabs.length;if(event.key==='ArrowLeft')next=(index-1+tabs.length)%tabs.length;if(event.key==='Home')next=0;if(event.key==='End')next=tabs.length-1;if(next!==undefined){event.preventDefault();selectPractice(tabs[next]);tabs[next].focus();}});});
const motion=window.matchMedia('(prefers-reduced-motion: reduce)');
const pointer=window.matchMedia('(hover: hover) and (pointer: fine)');
document.querySelectorAll('.project-cover').forEach(cover=>{cover.addEventListener('pointermove',event=>{if(motion.matches||!pointer.matches)return;const rect=cover.getBoundingClientRect();cover.style.setProperty('--mx',`${((event.clientX-rect.left)/rect.width-.5)*12}px`);cover.style.setProperty('--my',`${((event.clientY-rect.top)/rect.height-.5)*10}px`);});cover.addEventListener('pointerleave',()=>{cover.style.setProperty('--mx','0px');cover.style.setProperty('--my','0px');});});
